name: deepses_release
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - einops
  - h5py
  - tqdm
  - rich
  - pip
  - cytoolz
  - tmux
  - htop
  - matplotlib
  - pip:
    - torch # or if this fails because your driver is too old, install via pip wheel
    - tensorboard #NOTE: avoids mismatch with tensorboard utils of torch
    # pip install torch --index-url https://download.pytorch.org/whl/cuxxx, adjust to you cuda version!
    - onnx
    - onnxscript